version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web01
    depends_on:
      - app
      - mysql
    ports:
      - 8080:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/public:/var/www/html
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app01
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini
      - ./app/volumes:/var/www/html
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initialized:/docker-entrypoint-initdb.d
